version: '3.5'


services:

  postgres:
    image: postgres:9.6.6-alpine
    container_name: postgres
    restart: always
    networks:
      - emoji_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/db_backups:/db_backups
    env_file: ./deploy/secrets/dev.env

  app:
    image: sjbitcode/emoji-app
    build: ./app
    restart: always
    container_name: app
    networks:
      - emoji_network
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file: ./deploy/secrets/dev.env
    command: python manage.py runserver 0.0.0.0:8000
    # stdin_open: true
    # tty: true


volumes:
  pgdata:


networks:
  emoji_network:

