version: '3.5'


services:

  postgres:
    image: postgres:9.6.6-alpine
    container_name: postgres
    restart: always
    networks:
      - emoji_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/db_backups:/db_backups
    env_file: ./deploy/secrets/staging.env

  app:
    image: sjbitcode/emoji-app
    build: ./app
    restart: always
    container_name: app
    networks:
      - emoji_network
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
      - ./logs:/usr/src/logs
      - appstatic:/usr/src/app/static
    ports:
      - "8000:8000"
    env_file: ./deploy/secrets/staging.env
    command: gunicorn config.wsgi:application -c config/gunicornconfig.py

  web:
    image: sjbitcode/emoji-web
    build: ./web
    container_name: web
    volumes:
      - webdata:/usr/src/web


volumes: 
  pgdata:
  webdata:
    name: webdata
  appstatic:
    name: appstatic


networks:
  emoji_network:

