version: '3.5'


services:

  postgres:
    image: postgres:9.6.6-alpine
    container_name: postgres
    restart: always
    networks:
      - emoji_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: ./deploy/secrets/prod.env

  app:
    image: sjbitcode/emoji-app
    restart: always
    container_name: app
    networks:
      - emoji_network
    depends_on:
      - postgres
    volumes:
      - ./logs:/usr/src/logs
      - appstatic:/usr/src/app/static
    ports:
      - "8000:8000"
    env_file: ./deploy/secrets/prod.env
    command: gunicorn config.wsgi:application -c config/gunicornconfig.py

  web:
    image: sjbitcode/emoji-web
    container_name: web
    volumes:
      - webdata:/usr/src/web

  nginx:
    image: sjbitcode/emoji-nginx
    restart: always
    container_name: nginx
    volumes:
      - ./logs:/var/log/nginx
      - appstatic:/usr/src/appstatic
      - webdata:/usr/src/webdata
    ports:
      - "80:80"
    networks:
      - emoji_network
    depends_on:
      - app
      - web


volumes: 
  pgdata:
  webdata:
    name: webdata
  appstatic:
    name: appstatic


networks:
  emoji_network:

