version: '3.4'

services:
  postgres:
    image: postgres:9.6.6-alpine
    container_name: postgres
    restart: always
    networks:
      - emoji_network
    volumes:
         - pgdata:/var/lib/postgresql/data
    env_file: ./app/dev.env

  app:
    image: sjbitcode/emoji-app
    build: ./app
    restart: always
    container_name: app
    networks:
      - emoji_network
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file: ./app/dev.env
    command: python manage.py runserver 0.0.0.0:8000
    # stdin_open: true
    # tty: true


volumes: 
  pgdata:

networks:
  emoji_network:
