version: '3.5'

services:

  postgres:
    image: postgres:9.6.6-alpine
    container_name: postgres
    restart: always
    networks:
      - emoji_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: ./deploy/secrets/dev.env

  app:
    image: sjbitcode/emoji-app
    build: ./app
    restart: always
    container_name: app
    networks:
      - emoji_network
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
      # - ./logs:/usr/src/logs
      # - appstatic:/usr/src/app/static
    ports:
      - "8000:8000"
    env_file: ./deploy/secrets/dev.env
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn config.wsgi:application -c config/gunicornconfig.py
    # stdin_open: true
    # tty: true

  # web:
  #   image: sjbitcode/emoji-web
  #   build: ./web
  #   container_name: web
  #   volumes:
  #     - webdata:/usr/src/web

  # nginx:
  #   image: sjbitcode/emoji-nginx
  #   build: ./nginx
  #   restart: always
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./logs:/var/log/nginx
  #     - appstatic:/usr/src/appstatic
  #     - webdata:/usr/src/webdata
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - emoji_network
  #   depends_on:
  #     - app
  #     - web


volumes: 
  pgdata:
  # webdata:
  #   name: webdata
  # appstatic:
  #   name: appstatic


networks:
  emoji_network:

