# Generated by Django 2.0.2 on 2018-02-22 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('codepoint', models.CharField(help_text='Emoji Unicode UTF-8 Representation', max_length=150, verbose_name='UTF-8 Codepoint')),
                ('shortcode', models.CharField(help_text='Emoji Shortcode', max_length=200, verbose_name='Shortcode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Keyword Field for an Emoji', max_length=200, verbose_name='Emoji Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Main Category Field for an Emoji', max_length=100, verbose_name='Main Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Sub Category Field for an Emoji', max_length=100, verbose_name='Sub Category')),
                ('parent_category', models.ForeignKey(help_text='Emoji Sub Category', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='emojis.MainCategory', verbose_name='Sub Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnicodeVersion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(help_text='Unicode Version Release Year', verbose_name='Unicode Version Year')),
                ('number', models.CharField(help_text='Unicode Version Number', max_length=10, verbose_name='Unicode Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emoji',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Emoji Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emojis', to='emojis.SubCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='unicode_version',
            field=models.ForeignKey(help_text='Unicode Version', on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='emojis.UnicodeVersion', verbose_name='Unicode Version'),
        ),
    ]
