# Generated by Django 2.0.2 on 2018-02-23 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emojis', '0004_auto_20180223_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='main_category',
            field=models.ForeignKey(blank=True, help_text="This emoji's main category", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emojis', to='emojis.MainCategory', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='codepoint',
            field=models.CharField(help_text="This emoji's Unicode codepoints", max_length=150, verbose_name='UTF-8 Codepoint'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text="This emoji's keywords", related_name='emojis', to='emojis.Keyword', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='shortcode',
            field=models.CharField(help_text="This emoji's shortcode", max_length=200, verbose_name='Shortcode'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text="This emoji's sub category", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emojis', to='emojis.SubCategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='unicode_version',
            field=models.ForeignKey(blank=True, help_text="This emoji's unicode version", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='emojis.UnicodeVersion', verbose_name='Unicode Version'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(help_text='Keyword for an emoji', max_length=200, verbose_name='Emoji Keyword'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(help_text='Main category field for an emoji', max_length=100, verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Sub category field for an emoji', max_length=100, verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(help_text='The main category of this sub category', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='emojis.MainCategory', verbose_name='Main Parent Category'),
        ),
        migrations.AlterField(
            model_name='unicodeversion',
            name='number',
            field=models.CharField(help_text='Unicode version number', max_length=10, verbose_name='Unicode Version'),
        ),
        migrations.AlterField(
            model_name='unicodeversion',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Unicode version release year', verbose_name='Unicode Version Year'),
        ),
    ]
