# Generated by Django 2.0.2 on 2018-02-23 04:53

from django.db import migrations

def link_emoji_main_category(apps, schema_editor):
	'''
	Link the main category to an emoji directly
	via emoji.main_category instead of 
	following the Foreign Key from emoji.sub_category,
	like emoji.sub_category.parent_category.
	'''
	Emoji = apps.get_model('emojis', 'Emoji')
	SubCategory = apps.get_model('emojis', 'SubCategory')
	MainCategory = apps.get_model('emojis', 'MainCategory')

	for emoji in Emoji.objects.all():
		main_category = emoji.sub_category.parent_category
		emoji.main_category = main_category
		emoji.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emojis', '0005_auto_20180223_0448'),
    ]

    operations = [
    	migrations.RunPython(link_emoji_main_category)
    ]
